### ISSUE TITLE
named is crashing on cato

### ISSUE THREAD

**Issue by edwardtheharris** [edwardtheharris/lan#6]
This is happening with alarming regularity. 

```bash
[duchess@cato.dp:~]{0}> systemctl status named
● named.service - Internet domain name server
   Loaded: loaded (/usr/lib/systemd/system/named.service; enabled; vendor preset: disabled)
   Active: failed (Result: signal) since Mon 2018-11-26 17:54:39 PST; 1 day 2h ago
  Process: 27069 ExecStart=/usr/bin/named -f -u named (code=killed, signal=ABRT)
 Main PID: 27069 (code=killed, signal=ABRT)

Nov 26 17:54:38 cato.dp named[27069]: #1 0x7f8b6837ccaa in ??
Nov 26 17:54:38 cato.dp named[27069]: #2 0x7f8b6852f95b in ??
Nov 26 17:54:38 cato.dp named[27069]: #3 0x7f8b6853506e in ??
Nov 26 17:54:38 cato.dp named[27069]: #4 0x7f8b68538aba in ??
Nov 26 17:54:38 cato.dp named[27069]: #5 0x7f8b6839c349 in ??
Nov 26 17:54:38 cato.dp named[27069]: #6 0x7f8b6788ba9d in ??
Nov 26 17:54:38 cato.dp named[27069]: #7 0x7f8b677bbb23 in ??
Nov 26 17:54:38 cato.dp named[27069]: exiting (due to assertion failure)
Nov 26 17:54:39 cato.dp systemd[1]: named.service: Main process exited, code=killed, status=6/ABRT
Nov 26 17:54:39 cato.dp systemd[1]: named.service: Failed with result 'signal'.
```

**Comment by edwardtheharris** [comment]
Looks like [there's some insecurity going on](https://www.isc.org/blogs/summer_security_vulnerabilities/).

**Comment by edwardtheharris** [comment]
```bash
Nov 27 21:18:02 cato.dp named[17512]: configuring command channel from '/etc/rndc.key'
Nov 27 21:18:02 cato.dp named[17512]: command channel listening on 127.0.0.1#953
Nov 27 21:18:02 cato.dp named[17512]: configuring command channel from '/etc/rndc.key'
Nov 27 21:18:02 cato.dp named[17512]: command channel listening on ::1#953
```

This was an error before. One hopes it's related. We'll have to wait a day and see.

**Comment by edwardtheharris** [comment]
Looks like [the culprit](https://bugs.archlinux.org/task/60913) was an upgrade to a non-stable version of BIND.
